server:
  port: 8082

spring:
  application:
    name: EBS-CUSTOMER

  datasource:
    url: jdbc:postgresql://ep-dawn-salad-a7zuj372-pooler.ap-southeast-2.aws.neon.tech/customer?user=neondb_owner&password=npg_mjtW4uQNr8fB&sslmode=require&channelBinding=require
#    username: postgres
#    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  