spring:

  datasource:
    url: jdbc:postgresql://ep-dawn-salad-a7zuj372-pooler.ap-southeast-2.aws.neon.tech/fixed_deposite?user=neondb_owner&password=npg_mjtW4uQNr8fB&sslmode=require&channelBinding=require

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/