jwt:
  secret: banking-secret-key-very-secure-124
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://ep-dawn-salad-a7zuj372-pooler.ap-southeast-2.aws.neon.tech/auth?user=neondb_owner&password=npg_mjtW4uQNr8fB&sslmode=require&channelBinding=require
#    username: postgres
#    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true