server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:

          routes:

#            # AUTH SERVICE
#            - id: EBS-AUTH
#              uri: lb://EBS-AUTH
#              predicates:
#                - Path=/api/auth/**
#              filters:
#                - name: CircuitBreaker
#                  args:
#                    id: EBS-AUTH
#                    fallbackUri: forward:/accountServiceFallback

            # CUSTOMER SERVICE
            - id: EBS-CUSTOMER
              uri: lb://EBS-CUSTOMER
              predicates:
                - Path=/api/customers/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: EBS-CUSTOMER
                    fallbackUri: forward:/accountServiceFallback							
            # Auth SERVICE
            - id: EBS-AUTH
              uri: lb://EBS-AUTH
              predicates:
                - Path=/api/auth/**
            # ACCOUNT SERVICE
            - id: EBS-ACCOUNT
              uri: lb://EBS-ACCOUNT
              predicates:
                - Path=/api/accounts/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: EBS-ACCOUNT
                    fallbackUri: forward:/accountServiceFallback

            # TRANSACTION SERVICE
            - id: EBS-TRANSACTION
              uri: lb://EBS-TRANSACTION
              predicates:
                - Path=/api/transactions/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: EBS-TRANSACTION
                    fallbackUri: forward:/accountServiceFallback

            # FUND TRANSFER SERVICE
            - id: EBS-FUNDTRANSFER
              uri: lb://EBS-FUNDTRANSFER
              predicates:
                - Path=/api/transfers/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: EBS-FUNDTRANSFER
                    fallbackUri: forward:/accountServiceFallback

            # BENEFICIARY SERVICE
            - id: EBS-BENEFICIARY
              uri: lb://EBS-BENEFICIARY
              predicates:
                - Path=/api/beneficiaries/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: EBS-BENEFICIARY
                    fallbackUri: forward:/accountServiceFallback

            # STATEMENT SERVICE
            - id: EBS-STATEMENT
              uri: lb://EBS-STATEMENT
              predicates:
                - Path=/api/statements/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: EBS-STATEMENT
                    fallbackUri: forward:/accountServiceFallback

            # FIXED DEPOSIT SERVICE
            - id: EBS-FIXEDDEPOSIT
              uri: lb://EBS-FIXEDDEPOSIT
              predicates:
                - Path=/api/fixed-deposits/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: EBS-FIXEDDEPOSIT
                    fallbackUri: forward:/accountServiceFallback

            # NOTIFICATION SERVICE
            - id: EBS-NOTIFICATION
              uri: lb://EBS-NOTIFICATION
              predicates:
                - Path=/api/notifications/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: EBS-NOTIFICATION
                    fallbackUri: forward:/accountServiceFallback



eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/